language: php
env:
  global:
    secure: ZTlqiRvvpcgsLu/Q7n1Oq9MZPPnUiQc01IIay7QVE51uWYS6Nh4syMeLJo82ZUbA9f9BNwI3IbsEfwOw+JruggOfLRdzKK8P14T8VE+xyg7VnEbWkuYxlP3fjWft8itnhLZmK+78XRfTwlEp2rVui5BcjoBg3J1+vexhxu/NJnY=
before_install:
- sudo apt-get update
- sudo apt-get install -y doxygen ncftp
script:
- doxygen doxygen.config
after_success:
- ncftpput -R -v -u "ni109113_2ftp1" -p $ftppass ni109113_2.vweb17.nitrado.net /docs ./docs
