language: php
env:
  global:
    secure: OjZPjn5GGgeGpSBPqJ/9IYLLFEla/FraUMf1X8ztYVkciJQPwYTbtVUFX+dFZPsaeGi90f0JCl+ZSv9Q2AO/IjiMm33OC05cs2/4l32H6XkbnQyBnMUmwelQh0Leqx55x2ftul4Y56gK53y8tkAd3d+KJkRIfREsX4LvWlNcarE=
before_install:
- sudo apt-get update
- sudo apt-get install -y doxygen ncftp
script:
- doxygen doxygen.config
after_success:
- ncftpput -R -v -u "ni407250_3" -p $ftppass infymvc.org /docs ./docs
