language: php

sudo: false

env:
  global:
  - secure: fFJeIPv+Yng8ySNvPhE5AI01nhKEbuwWO+ZS6eGynttgZ689cnXS9gksTo8fiQ9cDXJ8axpFbbqerSRneydj5RYow5lEkAnKR5b2gmgi6txEJxl6NUaSmTHo5SOCZLRHJsp8jzfNESm9qUFaisk+UR+NqnkpI1So1mxfYp4LuOU=
  - secure: ACROTPC2td/Gxm2vdrDQLD3zE7phbgaoksIrqLdgQXPhx8JbD/5wFGcKqJJaHUjJchHG2NYQoOKYi6JzDZ5gQ3qjNRKjQ9LKny1CsredkP30JzSZp3ezwxX0Dineuy9Gn8FXaBQYVM7HdBf2MRp2qmnwmNiOn3zvWUVLtzmxaoc=
  - secure: Mf088j3Xz9+z1Dk2Dzzo4kFAPRVvJYWRDxCAqFoLilE2bSGR5qDuXh2kP9ixy5U9BP5AXXQabwIR4/KSM3NfUxb9rqRxIyqK3ObQgvKDuF62yursMMveA6LaM4u0WdN40CbM5cOSwofUFlGht+/Q/bImV+m+NtwMKI0z1Lf6+9E=

addons:
  apt:
    packages:
    - doxygen
    - ncftp

script:
- doxygen doxygen.config > /dev/null

after_success:
- ncftpput -R -v -u "$ftpuser" -p $ftppass $ftpip /docs ./docs/html/
